FROM ubuntu:20.04

# Copying the script that installs packages
COPY install_packages.sh /home/

# Making the script executable
RUN chmod +x /home/install_packages.sh

# Running the script to install packages
RUN /home/install_packages.sh

# Copying the Web_client script
COPY Web_Client.py /home/

# Making the script executable
RUN chmod +x /home/Web_Client.py

CMD ["bash"]
